name: Android CI Pull-Request Gradle Test

on:
  pull_request:
    branches:
      - main
      - android

jobs:
  Run-PR-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/build.gradle.kts', 'android/**/settings.gradle.kts', 'android/**/gradle-wrapper.properties', 'android/gradle/libs.versions.toml', 'android/**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties with BASE_URL
        run: |
          echo BASE_URL=\"${{ secrets.BASE_URL }}\" > local.properties
          echo NAVER_MAP_CLIENT_ID=\"${{ secrets.NAVER_MAP_CLIENT_ID }}\" >> local.properties
          echo NAVER_MAP_STYLE_ID=\"${{ secrets.NAVER_MAP_STYLE_ID }}\" >> local.properties

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$DATA" > app/google-services.json

      - name: Clean Project
        run: ./gradlew clean

      - name: Run ktlint
        run: ./gradlew ktlintCheck
        
      - name: Run Unit Test
        run: ./gradlew test

      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: android/app/build/test-results/**/TEST-*.xml
          check_name: 'í…ŒìŠ¤íŠ¸ ê²°ê³¼ ðŸ› ï¸'
          check_run_annotations: 'none'
          comment_mode: 'off'
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore keystore file
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/festabook_appkey.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build Release APK
        run: ./gradlew assembleRelease
